kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.Deployments.volName }}
  labels:
    type: local
    app: {{ .Values.Deployments.dbName }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.Deployments.volClaim }}
  labels:
    app: {{ .Values.Deployments.dbName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
